name: build-rbf
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # This is the specific raetro container used for the most complex MiSTer cores
    container:
      image: ghcr.io/raetro/quartus:mister
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile
        run: |
          # Use the quartus_sh command directly inside the container
          quartus_sh --flow compile Template.qpf
          
      - name: Upload RBF
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer-Core-RBF
          path: |
            *.rbf
            output_files/*.rbf
