name: build-rbf
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/raetro/quartus:mister
      # This is the "Magic Sauce" for 2026 compatibility
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # V3 is required for old glibc support

      - name: Compile
        run: |
          # Use the absolute path inside the raetro container
          /usr/local/quartus/bin/quartus_sh --flow compile Template.qpf
          
      - name: Upload RBF
        uses: actions/upload-artifact@v3 # V3 is required for old glibc support
        with:
          name: MiSTer-Core-RBF
          path: |
            *.rbf
            output_files/*.rbf
