name: build-rbf
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Core
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/build \
            -w /build \
            ghcr.io/raetro/quartus:mister \
            /bin/bash -c "/usr/local/quartus/bin/quartus_sh --flow compile Template.qpf"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer-Core
          path: |
            *.rbf
            output_files/*.rbf
