name: build-rbf
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile in Container
        # We run the Docker container as a single command instead of a job-wide setting
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/build \
            -w /build \
            ghcr.io/raetro/quartus:mister \
            /usr/local/quartus/bin/quartus_sh --flow compile Template.qpf
          
      - name: Upload RBF
        # This now runs on the "Host" Ubuntu (which is modern)
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer-Core
          path: |
            *.rbf
            output_files/*.rbf
