name: build-rbf
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build RBF
        # This action automatically finds the .qpf and handles the Docker environment for you
        uses: MiSTer-devel/gh-action-build@v0.6 
        with:
          project: 'Template'
          
      - name: Upload RBF
        uses: actions/upload-artifact@v4
        with:
          name: MiSTer-Core
          path: |
            *.rbf
            output_files/*.rbf
