- name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/raetro/quartus:mister
          options: -v ${{ github.workspace }}:/build
          run: |
            cd /build
            # Find the path to quartus_sh and execute it
            QPATH=$(find / -name quartus_sh -type f -executable -print -quit 2>/dev/null)
            echo "Found Quartus at: $QPATH"
            $QPATH --flow compile Template.qpf
